CUSTOM_FIELDS = {
    "Item": [
        {
            "fieldname": "item_name_abbreviation_kerp",
            "label": "Item Name Abbreviation",
            "fieldtype": "Data",
            "unique": "1",
            "depends_on": "eval:doc.has_variants && doc.is_stock_item",
            "mandatory_depends_on": "eval:doc.has_variants",
            "insert_after": "item_name",
        },
        {
            "fieldname": "item_assay_value_kerp",
            "label": "Assay Value",
            "fieldtype": "Link",
            "options": "Item Assay Value",
            "depends_on": "eval:!doc.has_variants && doc.is_stock_item && !doc.is_fixed_asset",
            "mandatory_depends_on": "eval:!doc.has_variants && doc.is_stock_item && !doc.is_fixed_asset",
            "insert_after": "section_break_11",
        },
        {
            "fieldname": "item_variant_name_kerp",
            "label": "Variant Name",
            "fieldtype": "Link",
            "options": "Item Variant Name",
            "depends_on": "eval:!doc.has_variants && doc.is_stock_item && !doc.is_fixed_asset",
            "mandatory_depends_on": "eval:!doc.has_variants && doc.is_stock_item && !doc.is_fixed_asset",
            "insert_after": "section_break_11",
        },
        {
            "fieldname": "column_break_1_kerp",
            "fieldtype": "Column Break",
            "insert_after": "description",
        },
        {
            "fieldname": "brand_item_reference_kerp",
            "label": "Brand Item Reference",
            "fieldtype": "Data",
            "description": 'Type "None" if not available',
            "depends_on": "eval:!doc.has_variants && doc.is_stock_item && !doc.is_fixed_asset",
            "mandatory_depends_on": "eval:!doc.has_variants && doc.is_stock_item && !doc.is_fixed_asset",
            "insert_after": "brand",
        },
        {
            "fieldname": "item_pack_size_kerp",
            "label": "Pack Size",
            "fieldtype": "Link",
            "options": "Item Pack Size",
            "depends_on": "eval:!doc.has_variants && doc.is_stock_item && !doc.is_fixed_asset",
            "mandatory_depends_on": "eval:!doc.has_variants && doc.is_stock_item && !doc.is_fixed_asset",
            "insert_after": "brand_item_reference_kerp",
        },
        {
            "fieldname": "item_physical_form_kerp",
            "label": "Physical Form",
            "fieldtype": "Link",
            "options": "Item Physical Form",
            "depends_on": "eval:!doc.has_variants && doc.is_stock_item && !doc.is_fixed_asset",
            "mandatory_depends_on": "eval:!doc.has_variants && doc.is_stock_item && !doc.is_fixed_asset",
            "insert_after": "item_pack_size_kerp",
        },
        {
            "fieldname": "item_physical_sub_form_kerp",
            "label": "Physical Sub-Form",
            "fieldtype": "Link",
            "options": "Item Physical Sub-Form",
            "depends_on": "eval:!doc.has_variants && doc.is_stock_item && !doc.is_fixed_asset",
            "mandatory_depends_on": "eval:!doc.has_variants && doc.is_stock_item && !doc.is_fixed_asset",
            "insert_after": "item_physical_form_kerp",
        },
        {
            "fieldname": "item_grade_kerp",
            "label": "Grade",
            "fieldtype": "Link",
            "options": "Item Grade",
            "depends_on": "eval:!doc.has_variants && doc.is_stock_item && !doc.is_fixed_asset",
            "mandatory_depends_on": "eval:!doc.has_variants && doc.is_stock_item && !doc.is_fixed_asset",
            "insert_after": "item_physical_sub_form_kerp",
        },
        {
            "fieldname": "item_grade_standard_kerp",
            "label": "Grade Standard",
            "fieldtype": "Link",
            "options": "Item Grade Standard",
            "depends_on": "eval:!doc.has_variants && doc.is_stock_item && !doc.is_fixed_asset",
            "mandatory_depends_on": "eval:!doc.has_variants && doc.is_stock_item && !doc.is_fixed_asset",
            "insert_after": "item_grade_kerp",
        },
    ],
    "Item Group": [
        {
            "fieldname": "abbreviation_kerp",
            "label": "Abbreviation",
            "fieldtype": "Data",
            "reqd": "1",
            "unique": "1",
            "insert_after": "item_group_name",
        },
    ],
    "Brand": [
        {
            "fieldname": "abbreviation_kerp",
            "label": "Abbreviation",
            "fieldtype": "Data",
            "reqd": "1",
            "unique": "1",
            "insert_after": "brand",
        },
        {
            "fieldname": "column_break_1_kerp",
            "fieldtype": "Column Break",
            "insert_after": "description",
        },
        {
            "fieldname": "manufacturers_kerp",
            "label": "Manufacturer Reference",
            "fieldtype": "Table",
            "options": "Manufacturer Reference",
            "insert_after": "column_break_1_kerp",
        },
    ],
    "Manufacturer": [
        {
            "fieldname": "abbreviation_kerp",
            "label": "Abbreviation",
            "fieldtype": "Data",
            "reqd": "1",
            "unique": "1",
            "insert_after": "full_name",
        },
    ],
    "Batch": [
        {
            "fieldname": "batch_no_kerp",
            "label": "Batch Number",
            "fieldtype": "Data",
            "read_only": "1",
            "depends_on": "eval:!doc.__islocal",
            "insert_after": "column_break_3",
        },
    ],
    "Customer": [
        {
            "fieldname": "customer_code_kerp",
            "label": "Customer Code",
            "fieldtype": "Data",
            "unique": "1",
            "read_only": "1",
            "no_copy": "1",
            "insert_after": "customer_name",
        },
        {
            "fieldname": "country_kerp",
            "label": "Country",
            "fieldtype": "Link",
            "options": "Country",
            "read_only_depends_on": "eval:!doc.__islocal",
            "mandatory_depends_on": "eval:doc.__islocal",
            "insert_after": "customer_group",
        },
    ],
    "Supplier": [
        {
            "fieldname": "supplier_code_kerp",
            "label": "Supplier Code",
            "fieldtype": "Data",
            "unique": "1",
            "read_only": "1",
            "no_copy": "1",
            "insert_after": "supplier_name",
        }
    ],
}
