import erpnext.stock.report.available_batch_report.available_batch_report
import erpnext.stock.report.batch_item_expiry_status.batch_item_expiry_status
import erpnext.stock.report.batch_wise_balance_history.batch_wise_balance_history
import erpnext.stock.report.serial_and_batch_summary.serial_and_batch_summary
import erpnext.stock.doctype.serial_and_batch_bundle.serial_and_batch_bundle
from kerp.overrides.available_batch_report.available_batch_report import execute as custom_available_batch_report_execute
from kerp.overrides.batch_item_expiry_status.batch_item_expiry_status import execute as custom_batch_item_expiry_status_execute
from kerp.overrides.batch_wise_balance_history.batch_wise_balance_history import execute as custom_batch_wise_balance_history_execute
from kerp.overrides.serial_and_batch_summary.serial_and_batch_summary import execute as custom_serial_and_batch_summary_execute
from kerp.overrides.serial_and_batch_bundle import get_qty_based_available_batches

erpnext.stock.report.available_batch_report.available_batch_report.execute = custom_available_batch_report_execute
erpnext.stock.report.batch_item_expiry_status.batch_item_expiry_status.execute = custom_batch_item_expiry_status_execute
erpnext.stock.report.batch_wise_balance_history.batch_wise_balance_history.execute = custom_batch_wise_balance_history_execute
erpnext.stock.report.serial_and_batch_summary.serial_and_batch_summary.execute = custom_serial_and_batch_summary_execute
erpnext.stock.doctype.serial_and_batch_bundle.serial_and_batch_bundle.get_qty_based_available_batches = get_qty_based_available_batches


__version__ = "15.0.0"
